version: "3.8"
x-default-logs: &default-opts
  logging:
    options:
      max-size: "1m"

x-master-opts: &master
  ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  discovery.seed_resolver.timeout: 60s
  discovery.seed_hosts: elastic-data-1,elastic-data-2,elastic-data-3
  cluster.initial_master_nodes: elastic-data-1,elastic-data-2,elastic-data-3
  cluster.name: "hive-cluster"
  network.host: 0.0.0.0
  node.master: "true"
  node.data: "true"
  node.ingest: "false"
  script.allowed_types: inline

x-data-opts: &data
  ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  discovery.seed_resolver.timeout: 60s
  discovery.seed_hosts: elastic-data-1,elastic-data-2,elastic-data-3
  cluster.initial_master_nodes: elastic-data-1,elastic-data-2,elastic-data-3
  cluster.name: "hive-cluster"
  network.host: 0.0.0.0
  node.master: "false"
  node.data: "true"
  node.ingest: "false"
  script.allowed_types: inline

x-cassandra-opts: &cassandra
  MAX_HEAP_SIZE: 1G
  HEAP_NEWSIZE: 1G
  CASSANDRA_CLUSTER_NAME: thp


services:

#########################################################################################################
### scylladb cluster
#########################################################################################################
  scylladb1:
    hostname: scylladb1
    image: cassandra:3.11
    environment:
      <<: *cassandra
    deploy:
      endpoint_mode: dnsrr
    networks:
      - thehive_cluster_net
    volumes:
      - "/mnt/mnt_docker/SIRP/thehive_cluster/scylla/data1/:/var/lib/scylla"
  scylladb2:
    hostname: scylladb2
    image: cassandra:3.11
    environment:
      <<: *cassandra
    deploy:
      endpoint_mode: dnsrr
    networks:
      - thehive_cluster_net
    volumes:
      - "/mnt/mnt_docker/SIRP/thehive_cluster/scylla/data2/:/var/lib/scylla"
  scylladb3:
    hostname: scylladb3
    image: cassandra:3.11
    environment:
      <<: *cassandra
    deploy:
      endpoint_mode: dnsrr
    networks:
      - thehive_cluster_net
    volumes:
      - "/mnt/mnt_docker/SIRP/thehive_cluster/scylla/data3/:/var/lib/scylla"

#########################################################################################################
### ELK cluster
#########################################################################################################
  elastic-data-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    healthcheck:
      test: curl -fs http://localhost:9200/_cat/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    environment:
      <<: *master
      node.name: "elastic-data-1"
    networks:
      thehive_cluster_net:
        aliases:
          - elastic-data-1
    volumes:
      - /mnt/mnt_docker/SIRP/thehive_cluster/esindex1:/usr/share/elasticsearch/data
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 1G

  elastic-data-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    healthcheck:
      test: curl -fs http://localhost:9200/_cat/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    environment:
      <<: *master
      node.name: "elastic-data-2"
    networks:
      thehive_cluster_net:
        aliases:
          - elastic-data-2
    volumes:
      - /mnt/mnt_docker/SIRP/thehive_cluster/esindex2:/usr/share/elasticsearch/data
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 1G

  elastic-data-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    healthcheck:
      test: curl -fs http://localhost:9200/_cat/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    environment:
      <<: *master
      node.name: "elastic-data-3"
    networks:
      thehive_cluster_net:
        aliases:
          - elastic-data-3
    volumes:
      - /mnt/mnt_docker/SIRP/thehive_cluster/esindex3:/usr/share/elasticsearch/data
    deploy:
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 1G

#########################################################################################################
### Thehive cluster
#########################################################################################################
  thehive1:
    hostname: thehive1
    image: "thehiveproject/thehive4:latest"
    restart: unless-stopped
    networks:
      - thehive_cluster_net

    ports:
      - "0.0.0.0:9001:9000"
    volumes:
      - /mnt/mnt_docker/SIRP/thehive_cluster/thehive1/application.conf:/etc/thehive/application.conf
      - /mnt/mnt_docker/SIRP/thehive_cluster/thehive1/lucene:/opt/thp/thehive/index
      - /mnt/mnt_docker/SIRP/thehive_cluster/shared_data/:/opt/thp/thehive/data
    command: "--no-config --no-config-secret"

  thehive2:
    hostname: thehive2
    image: "thehiveproject/thehive4:latest"
    restart: unless-stopped
    networks:
      - thehive_cluster_net

    ports:
      - "0.0.0.0:9002:9000"
    volumes:
      - /mnt/mnt_docker/SIRP/thehive_cluster/thehive2/application.conf:/etc/thehive/application.conf
      - /mnt/mnt_docker/SIRP/thehive_cluster/thehive2/lucene:/opt/thp/thehive/index
      - /mnt/mnt_docker/SIRP/thehive_cluster/shared_data/:/opt/thp/thehive/data
    command: "--no-config --no-config-secret"

  thehive3:
    hostname: thehive3
    image: "thehiveproject/thehive4:latest"
    restart: unless-stopped
    networks:
      - thehive_cluster_net
    ports:
      - "0.0.0.0:9003:9000"

    volumes:
      - /mnt/mnt_docker/SIRP/thehive_cluster/thehive3/application.conf:/etc/thehive/application.conf
      - /mnt/mnt_docker/SIRP/thehive_cluster/thehive3/lucene:/opt/thp/thehive/index
      - /mnt/mnt_docker/SIRP/thehive_cluster/shared_data/:/opt/thp/thehive/data
    command: "--no-config --no-config-secret"

#########################################################################################################
### Network
#########################################################################################################

networks:
  thehive_cluster_net:
    driver: overlay
    attachable: true
